/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Chart: typeof import('./../components/Chart/index.vue')['default']
    GhostButton: typeof import('./../components/GhostButton.vue')['default']
    GuideOverlay: typeof import('./../components/GuideOverlay.vue')['default']
    IconSvg: typeof import('./../components/IconSvg.vue')['default']
    ImagePreview: typeof import('./../components/ImagePreview.vue')['default']
    LangSwitcher: typeof import('./../components/LangSwitcher.vue')['default']
    Login: typeof import('./../components/Login.vue')['default']
    LogoutButton: typeof import('./../components/LogoutButton.vue')['default']
    NavBar: typeof import('./../components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tab: typeof import('./../components/Tab.vue')['default']
    TabBar: typeof import('./../components/TabBar.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanLoading: typeof import('vant/es')['Loading']
    VanPopup: typeof import('vant/es')['Popup']
    VanSpace: typeof import('vant/es')['Space']
    VanStepper: typeof import('vant/es')['Stepper']
    VanSwitch: typeof import('vant/es')['Switch']
    VanUploader: typeof import('vant/es')['Uploader']
    VideoPlayer: typeof import('./../components/VideoPlayer.vue')['default']
    VideoPreview: typeof import('./../components/VideoPreview.vue')['default']
  }
}
