/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '404': RouteRecordInfo<'404', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/image': RouteRecordInfo<'/admin/image', '/admin/image', Record<never, never>, Record<never, never>>,
    '/admin/print': RouteRecordInfo<'/admin/print', '/admin/print', Record<never, never>, Record<never, never>>,
    '/admin/video': RouteRecordInfo<'/admin/video', '/admin/video', Record<never, never>, Record<never, never>>,
    '/creation/': RouteRecordInfo<'/creation/', '/creation', Record<never, never>, Record<never, never>>,
    '/creation/[type]': RouteRecordInfo<'/creation/[type]', '/creation/:type', { type: ParamValue<true> }, { type: ParamValue<false> }>,
    'KeepAlive': RouteRecordInfo<'KeepAlive', '/keepalive', Record<never, never>, Record<never, never>>,
    'mock': RouteRecordInfo<'mock', '/mock', Record<never, never>, Record<never, never>>,
    '/qr/': RouteRecordInfo<'/qr/', '/qr', Record<never, never>, Record<never, never>>,
    '/qr/[type]': RouteRecordInfo<'/qr/[type]', '/qr/:type', { type: ParamValue<true> }, { type: ParamValue<false> }>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    '/screen/': RouteRecordInfo<'/screen/', '/screen', Record<never, never>, Record<never, never>>,
    '/screen/image': RouteRecordInfo<'/screen/image', '/screen/image', Record<never, never>, Record<never, never>>,
    '/screen/video': RouteRecordInfo<'/screen/video', '/screen/video', Record<never, never>, Record<never, never>>,
  }
}
