spring:
  application:
    name: kling-waic-express-server-api
  config:
    import:
      - optional:classpath:application-env.properties
      - optional:file:/app/application-env.properties
  mvc:
    servlet:
      path: /api
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8538

waic:
  jwt:
    expireAtInSeconds: 1800
    notBeforeInSeconds: -5

kling:
  open-api:
    base-url: https://api-beijing.klingai.com
