spring:
  application:
    name: kling-waic-express-server
  mvc:
    servlet:
      path: /api
  web:
    resources:
      static-locations: file:${waic.sudoku.images-dir}/

server:
  port: 8538

jedis:
  host: 43.196.50.81
  port: 6379

waic:
  jwt:
    expireAtInSeconds: 1800
    notBeforeInSeconds: -5
  sudoku:
    images-dir: ${SUDOKU_IMAGES_DIR:./sudoku-images}
    url-prefix: ${SUDOKU_IMAGES_URL_PREFIX:/sudoku-images}
    server-domain: ${SUDOKU_IMAGES_SERVER_DOMAIN:localhost:8538}

kling:
  open-api:
    base-url: https://api-beijing.klingai.com
