spring:
  application:
    name: kling-waic-express-server
  config:
    import: optional:file:.env
  mvc:
    servlet:
      path: /api
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
#  web:
#    resources:
#      static-locations: file:${waic.sudoku.images-dir}/

server:
  port: 8538

jedis:
  host: 172.28.199.165
  port: 6379
  password: ${REDIS_PASS_WAIC}

waic:
  jwt:
    expireAtInSeconds: 1800
    notBeforeInSeconds: -5
  sudoku:
    images-dir: ${SUDOKU_IMAGES_DIR:./sudoku-images}
    url-prefix: ${SUDOKU_IMAGES_URL_PREFIX:/sudoku-images}
    server-domain: ${SUDOKU_IMAGES_SERVER_DOMAIN:localhost:8538}
  management:
    token: ${WAIC_MANAGEMENT_TOKEN}
  open-api:
    access-key: ${WAIC_OPENAPI_ACCESS_KEY}
    secret-key: ${WAIC_OPENAPI_SECRET_KEY}

kling:
  open-api:
    base-url: https://api-beijing.klingai.com
  proxy:
    host: 10.52.57.90
    port: 11080
