version: '3.9'

services:
  kling-waic-express:
    image: maven:3.9.9-amazoncorretto-17
    container_name: kling-waic-express
    working_dir: /app
    volumes:
      - ~/.m2:/root/.m2
      - ./:/app
    ports:
      - "10238:8538"
    command: mvn spring-boot:run
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
